# Generated by Django 4.0.3 on 2022-04-14 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RezhApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RezhApp.article')),
                ('company', models.CharField(max_length=255)),
                ('contacts', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
            ],
            bases=('RezhApp.article',),
        ),
    ]
