# Generated by Django 4.0.4 on 2022-04-21 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RezhApp', '0003_articleimage_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='RezhApp.article'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
