# Generated by Django 4.0.4 on 2022-06-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RezhApp', '0004_alter_articleimage_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
    ]
