# Generated by Django 4.0.4 on 2022-06-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RezhApp', '0005_history_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='nested',
            field=models.BooleanField(default=False),
        ),
    ]
