# Generated by Django 4.0.4 on 2022-06-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RezhApp', '0006_history_nested'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='description',
            field=models.TextField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='short_descriptin',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='company',
            field=models.CharField(max_length=128),
        ),
    ]
