# Generated by Django 4.0.4 on 2022-06-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RezhApp', '0007_jobs_description_jobs_short_descriptin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='description',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='short_descriptin',
        ),
        migrations.AlterField(
            model_name='article',
            name='short',
            field=models.CharField(blank=True, default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='caption',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='company',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
