# Generated by Django 4.0.4 on 2022-06-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RezhApp', '0008_remove_jobs_description_remove_jobs_short_descriptin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
